#include "stdafx.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DesignEvent.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "DesignEvent.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ProtocolBuffers {
namespace GameAnalytics {

namespace {

const ::google::protobuf::Descriptor* DesignEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DesignEvent_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_DesignEvent_2eproto() {
  protobuf_AddDesc_DesignEvent_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "DesignEvent.proto");
  GOOGLE_CHECK(file != NULL);
  DesignEvent_descriptor_ = file->message_type(0);
  static const int DesignEvent_offsets_[1] = {
  };
  DesignEvent_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DesignEvent_descriptor_,
      DesignEvent::default_instance_,
      DesignEvent_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DesignEvent, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DesignEvent, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DesignEvent));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_DesignEvent_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DesignEvent_descriptor_, &DesignEvent::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_DesignEvent_2eproto() {
  delete DesignEvent::default_instance_;
  delete DesignEvent_reflection_;
}

void protobuf_AddDesc_DesignEvent_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ProtocolBuffers::GameAnalytics::protobuf_AddDesc_Event_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021DesignEvent.proto\022\035ProtocolBuffers.Gam"
    "eAnalytics\032\013Event.proto\"B\n\013DesignEvent23"
    "\n\005value\022$.ProtocolBuffers.GameAnalytics."
    "Event\030d \001(\002", 131);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DesignEvent.proto", &protobuf_RegisterTypes);
  DesignEvent::default_instance_ = new DesignEvent();
  DesignEvent::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    100, 2, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_DesignEvent_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_DesignEvent_2eproto {
  StaticDescriptorInitializer_DesignEvent_2eproto() {
    protobuf_AddDesc_DesignEvent_2eproto();
  }
} static_descriptor_initializer_DesignEvent_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

#ifndef _MSC_VER
const int DesignEvent::kValueFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::PrimitiveTypeTraits< float >, 2, false >
  DesignEvent::value(kValueFieldNumber, 0);
DesignEvent::DesignEvent()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DesignEvent::InitAsDefaultInstance() {
}

DesignEvent::DesignEvent(const DesignEvent& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DesignEvent::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DesignEvent::~DesignEvent() {
  SharedDtor();
}

void DesignEvent::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DesignEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DesignEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DesignEvent_descriptor_;
}

const DesignEvent& DesignEvent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_DesignEvent_2eproto();
  return *default_instance_;
}

DesignEvent* DesignEvent::default_instance_ = NULL;

DesignEvent* DesignEvent::New() const {
  return new DesignEvent;
}

void DesignEvent::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DesignEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void DesignEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DesignEvent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DesignEvent::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DesignEvent::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DesignEvent* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DesignEvent*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DesignEvent::MergeFrom(const DesignEvent& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DesignEvent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DesignEvent::CopyFrom(const DesignEvent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DesignEvent::IsInitialized() const {

  return true;
}

void DesignEvent::Swap(DesignEvent* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DesignEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DesignEvent_descriptor_;
  metadata.reflection = DesignEvent_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameAnalytics
}  // namespace ProtocolBuffers

// @@protoc_insertion_point(global_scope)
