// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DesignEvent.proto

#ifndef PROTOBUF_DesignEvent_2eproto__INCLUDED
#define PROTOBUF_DesignEvent_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Event.pb.h"
// @@protoc_insertion_point(includes)

namespace ProtocolBuffers {
namespace GameAnalytics {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_DesignEvent_2eproto();
void protobuf_AssignDesc_DesignEvent_2eproto();
void protobuf_ShutdownFile_DesignEvent_2eproto();

class DesignEvent;

// ===================================================================

class DesignEvent : public ::google::protobuf::Message {
 public:
  DesignEvent();
  virtual ~DesignEvent();

  DesignEvent(const DesignEvent& from);

  inline DesignEvent& operator=(const DesignEvent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DesignEvent& default_instance();

  void Swap(DesignEvent* other);

  // implements Message ----------------------------------------------

  DesignEvent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DesignEvent& from);
  void MergeFrom(const DesignEvent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  static const int kValueFieldNumber = 100;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::PrimitiveTypeTraits< float >, 2, false >
    value;
  // @@protoc_insertion_point(class_scope:ProtocolBuffers.GameAnalytics.DesignEvent)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_DesignEvent_2eproto();
  friend void protobuf_AssignDesc_DesignEvent_2eproto();
  friend void protobuf_ShutdownFile_DesignEvent_2eproto();

  void InitAsDefaultInstance();
  static DesignEvent* default_instance_;
};
// ===================================================================


// ===================================================================

// DesignEvent


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameAnalytics
}  // namespace ProtocolBuffers

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DesignEvent_2eproto__INCLUDED
