#include "stdafx.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorEvent.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ErrorEvent.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ProtocolBuffers {
namespace GameAnalytics {

namespace {

const ::google::protobuf::Descriptor* ErrorEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ErrorEvent_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ErrorEvent_2eproto() {
  protobuf_AddDesc_ErrorEvent_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ErrorEvent.proto");
  GOOGLE_CHECK(file != NULL);
  ErrorEvent_descriptor_ = file->message_type(0);
  static const int ErrorEvent_offsets_[1] = {
  };
  ErrorEvent_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ErrorEvent_descriptor_,
      ErrorEvent::default_instance_,
      ErrorEvent_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorEvent, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ErrorEvent, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ErrorEvent));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ErrorEvent_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ErrorEvent_descriptor_, &ErrorEvent::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ErrorEvent_2eproto() {
  delete ErrorEvent::default_instance_;
  delete ErrorEvent_reflection_;
}

void protobuf_AddDesc_ErrorEvent_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ProtocolBuffers::GameAnalytics::protobuf_AddDesc_Event_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020ErrorEvent.proto\022\035ProtocolBuffers.Game"
    "Analytics\032\013Event.proto\"}\n\nErrorEvent26\n\007"
    "message\022$.ProtocolBuffers.GameAnalytics."
    "Event\030\226\001 \001(\t27\n\010severity\022$.ProtocolBuffe"
    "rs.GameAnalytics.Event\030\227\001 \001(\t", 189);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ErrorEvent.proto", &protobuf_RegisterTypes);
  ErrorEvent::default_instance_ = new ErrorEvent();
  ErrorEvent::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    150, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    151, 9, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ErrorEvent_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ErrorEvent_2eproto {
  StaticDescriptorInitializer_ErrorEvent_2eproto() {
    protobuf_AddDesc_ErrorEvent_2eproto();
  }
} static_descriptor_initializer_ErrorEvent_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

const ::std::string ErrorEvent_message_default("");
#ifndef _MSC_VER
const int ErrorEvent::kMessageFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  ErrorEvent::message(kMessageFieldNumber, ErrorEvent_message_default);
const ::std::string ErrorEvent_severity_default("");
#ifndef _MSC_VER
const int ErrorEvent::kSeverityFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  ErrorEvent::severity(kSeverityFieldNumber, ErrorEvent_severity_default);
ErrorEvent::ErrorEvent()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ErrorEvent::InitAsDefaultInstance() {
}

ErrorEvent::ErrorEvent(const ErrorEvent& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ErrorEvent::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ErrorEvent::~ErrorEvent() {
  SharedDtor();
}

void ErrorEvent::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ErrorEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ErrorEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ErrorEvent_descriptor_;
}

const ErrorEvent& ErrorEvent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ErrorEvent_2eproto();
  return *default_instance_;
}

ErrorEvent* ErrorEvent::default_instance_ = NULL;

ErrorEvent* ErrorEvent::New() const {
  return new ErrorEvent;
}

void ErrorEvent::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ErrorEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void ErrorEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ErrorEvent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ErrorEvent::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ErrorEvent::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ErrorEvent* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ErrorEvent*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ErrorEvent::MergeFrom(const ErrorEvent& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ErrorEvent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ErrorEvent::CopyFrom(const ErrorEvent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ErrorEvent::IsInitialized() const {

  return true;
}

void ErrorEvent::Swap(ErrorEvent* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ErrorEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ErrorEvent_descriptor_;
  metadata.reflection = ErrorEvent_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameAnalytics
}  // namespace ProtocolBuffers

// @@protoc_insertion_point(global_scope)
