// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserEvent.proto

#ifndef PROTOBUF_UserEvent_2eproto__INCLUDED
#define PROTOBUF_UserEvent_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Event.pb.h"
// @@protoc_insertion_point(includes)

namespace ProtocolBuffers {
namespace GameAnalytics {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UserEvent_2eproto();
void protobuf_AssignDesc_UserEvent_2eproto();
void protobuf_ShutdownFile_UserEvent_2eproto();

class UserEvent;

// ===================================================================

class UserEvent : public ::google::protobuf::Message {
 public:
  UserEvent();
  virtual ~UserEvent();

  UserEvent(const UserEvent& from);

  inline UserEvent& operator=(const UserEvent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserEvent& default_instance();

  void Swap(UserEvent* other);

  // implements Message ----------------------------------------------

  UserEvent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserEvent& from);
  void MergeFrom(const UserEvent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  static const int kGenderFieldNumber = 51;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    gender;
  static const int kBirthYearFieldNumber = 52;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
    birth_year;
  static const int kFriendCountFieldNumber = 53;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
    friend_count;
  static const int kFacebookIdFieldNumber = 54;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    facebook_id;
  static const int kGoogleplusIdFieldNumber = 55;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    googleplus_id;
  static const int kIosIdFieldNumber = 56;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    ios_id;
  static const int kAndroidIdFieldNumber = 57;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    android_id;
  static const int kAdtruthIdFieldNumber = 58;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    adtruth_id;
  static const int kPlatformFieldNumber = 59;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    platform;
  static const int kDeviceFieldNumber = 60;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    device;
  static const int kOsMajorFieldNumber = 61;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    os_major;
  static const int kOsMinorFieldNumber = 62;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    os_minor;
  static const int kInstallPublisherFieldNumber = 63;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    install_publisher;
  static const int kInstallSiteFieldNumber = 64;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    install_site;
  static const int kInstallCampaignFieldNumber = 65;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    install_campaign;
  static const int kInstallAdgroupFieldNumber = 66;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    install_adgroup;
  static const int kInstallAdFieldNumber = 67;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    install_ad;
  static const int kInstallKeywordFieldNumber = 68;
  static ::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
      ::google::protobuf::internal::StringTypeTraits, 9, false >
    install_keyword;
  // @@protoc_insertion_point(class_scope:ProtocolBuffers.GameAnalytics.UserEvent)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_UserEvent_2eproto();
  friend void protobuf_AssignDesc_UserEvent_2eproto();
  friend void protobuf_ShutdownFile_UserEvent_2eproto();

  void InitAsDefaultInstance();
  static UserEvent* default_instance_;
};
// ===================================================================


// ===================================================================

// UserEvent


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameAnalytics
}  // namespace ProtocolBuffers

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UserEvent_2eproto__INCLUDED
