#include "stdafx.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserEvent.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "UserEvent.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ProtocolBuffers {
namespace GameAnalytics {

namespace {

const ::google::protobuf::Descriptor* UserEvent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UserEvent_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_UserEvent_2eproto() {
  protobuf_AddDesc_UserEvent_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "UserEvent.proto");
  GOOGLE_CHECK(file != NULL);
  UserEvent_descriptor_ = file->message_type(0);
  static const int UserEvent_offsets_[1] = {
  };
  UserEvent_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UserEvent_descriptor_,
      UserEvent::default_instance_,
      UserEvent_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserEvent, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserEvent, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UserEvent));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_UserEvent_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UserEvent_descriptor_, &UserEvent::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_UserEvent_2eproto() {
  delete UserEvent::default_instance_;
  delete UserEvent_reflection_;
}

void protobuf_AddDesc_UserEvent_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ProtocolBuffers::GameAnalytics::protobuf_AddDesc_Event_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017UserEvent.proto\022\035ProtocolBuffers.GameA"
    "nalytics\032\013Event.proto\"\254\010\n\tUserEvent24\n\006g"
    "ender\022$.ProtocolBuffers.GameAnalytics.Ev"
    "ent\0303 \001(\t28\n\nbirth_year\022$.ProtocolBuffer"
    "s.GameAnalytics.Event\0304 \001(\0052:\n\014friend_co"
    "unt\022$.ProtocolBuffers.GameAnalytics.Even"
    "t\0305 \001(\00529\n\013facebook_id\022$.ProtocolBuffers"
    ".GameAnalytics.Event\0306 \001(\t2;\n\rgoogleplus"
    "_id\022$.ProtocolBuffers.GameAnalytics.Even"
    "t\0307 \001(\t24\n\006ios_id\022$.ProtocolBuffers.Game"
    "Analytics.Event\0308 \001(\t28\n\nandroid_id\022$.Pr"
    "otocolBuffers.GameAnalytics.Event\0309 \001(\t2"
    "8\n\nadtruth_id\022$.ProtocolBuffers.GameAnal"
    "ytics.Event\030: \001(\t26\n\010platform\022$.Protocol"
    "Buffers.GameAnalytics.Event\030; \001(\t24\n\006dev"
    "ice\022$.ProtocolBuffers.GameAnalytics.Even"
    "t\030< \001(\t26\n\010os_major\022$.ProtocolBuffers.Ga"
    "meAnalytics.Event\030= \001(\t26\n\010os_minor\022$.Pr"
    "otocolBuffers.GameAnalytics.Event\030> \001(\t2"
    "\?\n\021install_publisher\022$.ProtocolBuffers.G"
    "ameAnalytics.Event\030\? \001(\t2:\n\014install_site"
    "\022$.ProtocolBuffers.GameAnalytics.Event\030@"
    " \001(\t2>\n\020install_campaign\022$.ProtocolBuffe"
    "rs.GameAnalytics.Event\030A \001(\t2=\n\017install_"
    "adgroup\022$.ProtocolBuffers.GameAnalytics."
    "Event\030B \001(\t28\n\ninstall_ad\022$.ProtocolBuff"
    "ers.GameAnalytics.Event\030C \001(\t2=\n\017install"
    "_keyword\022$.ProtocolBuffers.GameAnalytics"
    ".Event\030D \001(\t", 1132);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "UserEvent.proto", &protobuf_RegisterTypes);
  UserEvent::default_instance_ = new UserEvent();
  UserEvent::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    51, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    52, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    53, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    54, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    55, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    56, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    57, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    58, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    59, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    60, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    61, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    62, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    63, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    64, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    65, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    66, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    67, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::ProtocolBuffers::GameAnalytics::Event::default_instance(),
    68, 9, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_UserEvent_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_UserEvent_2eproto {
  StaticDescriptorInitializer_UserEvent_2eproto() {
    protobuf_AddDesc_UserEvent_2eproto();
  }
} static_descriptor_initializer_UserEvent_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

const ::std::string UserEvent_gender_default("");
#ifndef _MSC_VER
const int UserEvent::kGenderFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::gender(kGenderFieldNumber, UserEvent_gender_default);
#ifndef _MSC_VER
const int UserEvent::kBirthYearFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  UserEvent::birth_year(kBirthYearFieldNumber, 0);
#ifndef _MSC_VER
const int UserEvent::kFriendCountFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  UserEvent::friend_count(kFriendCountFieldNumber, 0);
const ::std::string UserEvent_facebook_id_default("");
#ifndef _MSC_VER
const int UserEvent::kFacebookIdFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::facebook_id(kFacebookIdFieldNumber, UserEvent_facebook_id_default);
const ::std::string UserEvent_googleplus_id_default("");
#ifndef _MSC_VER
const int UserEvent::kGoogleplusIdFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::googleplus_id(kGoogleplusIdFieldNumber, UserEvent_googleplus_id_default);
const ::std::string UserEvent_ios_id_default("");
#ifndef _MSC_VER
const int UserEvent::kIosIdFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::ios_id(kIosIdFieldNumber, UserEvent_ios_id_default);
const ::std::string UserEvent_android_id_default("");
#ifndef _MSC_VER
const int UserEvent::kAndroidIdFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::android_id(kAndroidIdFieldNumber, UserEvent_android_id_default);
const ::std::string UserEvent_adtruth_id_default("");
#ifndef _MSC_VER
const int UserEvent::kAdtruthIdFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::adtruth_id(kAdtruthIdFieldNumber, UserEvent_adtruth_id_default);
const ::std::string UserEvent_platform_default("");
#ifndef _MSC_VER
const int UserEvent::kPlatformFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::platform(kPlatformFieldNumber, UserEvent_platform_default);
const ::std::string UserEvent_device_default("");
#ifndef _MSC_VER
const int UserEvent::kDeviceFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::device(kDeviceFieldNumber, UserEvent_device_default);
const ::std::string UserEvent_os_major_default("");
#ifndef _MSC_VER
const int UserEvent::kOsMajorFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::os_major(kOsMajorFieldNumber, UserEvent_os_major_default);
const ::std::string UserEvent_os_minor_default("");
#ifndef _MSC_VER
const int UserEvent::kOsMinorFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::os_minor(kOsMinorFieldNumber, UserEvent_os_minor_default);
const ::std::string UserEvent_install_publisher_default("");
#ifndef _MSC_VER
const int UserEvent::kInstallPublisherFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::install_publisher(kInstallPublisherFieldNumber, UserEvent_install_publisher_default);
const ::std::string UserEvent_install_site_default("");
#ifndef _MSC_VER
const int UserEvent::kInstallSiteFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::install_site(kInstallSiteFieldNumber, UserEvent_install_site_default);
const ::std::string UserEvent_install_campaign_default("");
#ifndef _MSC_VER
const int UserEvent::kInstallCampaignFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::install_campaign(kInstallCampaignFieldNumber, UserEvent_install_campaign_default);
const ::std::string UserEvent_install_adgroup_default("");
#ifndef _MSC_VER
const int UserEvent::kInstallAdgroupFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::install_adgroup(kInstallAdgroupFieldNumber, UserEvent_install_adgroup_default);
const ::std::string UserEvent_install_ad_default("");
#ifndef _MSC_VER
const int UserEvent::kInstallAdFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::install_ad(kInstallAdFieldNumber, UserEvent_install_ad_default);
const ::std::string UserEvent_install_keyword_default("");
#ifndef _MSC_VER
const int UserEvent::kInstallKeywordFieldNumber;
#endif
::google::protobuf::internal::ExtensionIdentifier< ::ProtocolBuffers::GameAnalytics::Event,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  UserEvent::install_keyword(kInstallKeywordFieldNumber, UserEvent_install_keyword_default);
UserEvent::UserEvent()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void UserEvent::InitAsDefaultInstance() {
}

UserEvent::UserEvent(const UserEvent& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void UserEvent::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UserEvent::~UserEvent() {
  SharedDtor();
}

void UserEvent::SharedDtor() {
  if (this != default_instance_) {
  }
}

void UserEvent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserEvent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UserEvent_descriptor_;
}

const UserEvent& UserEvent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_UserEvent_2eproto();
  return *default_instance_;
}

UserEvent* UserEvent::default_instance_ = NULL;

UserEvent* UserEvent::New() const {
  return new UserEvent;
}

void UserEvent::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UserEvent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void UserEvent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* UserEvent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int UserEvent::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UserEvent::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UserEvent* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UserEvent*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UserEvent::MergeFrom(const UserEvent& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UserEvent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserEvent::CopyFrom(const UserEvent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserEvent::IsInitialized() const {

  return true;
}

void UserEvent::Swap(UserEvent* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UserEvent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UserEvent_descriptor_;
  metadata.reflection = UserEvent_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameAnalytics
}  // namespace ProtocolBuffers

// @@protoc_insertion_point(global_scope)
